### ISSUE TITLE
Ordering of events

### ISSUE THREAD

**Issue by adamamyl** [rewiredstate/hacks#1]
We had to add (skeleton) information for past-events to the Hacks App, but it seems to expect events to be added in chronological order.

Can "we" add an ordering functionality; either 'position' or 'start/end dates' that would be sorted against, with most recent first (at the top)?

**Comment by JordanHatch** [comment]
I've added a start date field to each event (see pull #2) which is then used to sort the events list.

You'll need to go through each event and give it a date, though. I've added the first couple.

**Comment by adamamyl** [comment]
Dates added, and sorting works fine. Thank you
